version: '3.9'
services:

  nginx:
    image: nginx:1.25-alpine
    container_name: ${NGINX_HOST}
    restart: always
    env_file: .env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx/access.log:/var/log/nginx/access.log
      - ./nginx/error.log:/var/log/nginx/error.log

  cron:
    image: cron-i
    build: 
      context: ./cron
      dockerfile: Dockerfile
    container_name: ${CRON_HOST}
    restart: always
    env_file: .env
    volumes:
      - ./cron/cron.log:/var/log/cron.log
      - ./nginx/access.log:/var/log/nginx/access.log:ro
      - ./nginx/error.log:/var/log/nginx/error.log:ro
    depends_on:
      - nginx